In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
import joblib
%matplotlib inline

In [2]:
# Loading Dataset
traffic = pd.read_csv('Mirai_dataset.csv', sep=',')

In [3]:
# seeing info for the file
traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764136 entries, 0 to 764135
Columns: 117 entries, null to attack
dtypes: float64(115), int64(2)
memory usage: 682.1 MB

In [4]:
# Seeing first five rows with headers
traffic.head()

,null,null.1,null.2,null.3,null.4,null.5,null.6,null.7,null.8,null.9,...,null.107,null.108,null.109,null.110,null.111,null.112,null.113,null.114,null.115,attack
0,1,1.999983,60.0,0.000000e+00,1.999990,60.0,9.094947e-13,1.999997,60.0,4.547474e-13,...,0.0,0.0,1.0,60.0,0.0,60.0,0.0,0.0,0.0,0
1,2,1.000000,86.0,0.000000e+00,1.000000,86.0,0.000000e+00,1.000000,86.0,0.000000e+00,...,0.0,0.0,1.0,86.0,0.0,86.0,0.0,0.0,0.0,0
2,3,1.999272,86.0,9.094947e-13,1.999563,86.0,0.000000e+00,1.999854,86.0,9.094947e-13,...,0.0,0.0,1.0,86.0,0.0,86.0,0.0,0.0,0.0,0
3,4,1.000000,60.0,0.000000e+00,1.000000,60.0,0.000000e+00,1.000000,60.0,0.000000e+00,...,0.0,0.0,1.0,60.0,0.0,60.0,0.0,0.0,0.0,0
4,5,1.000000,74.0,0.000000e+00,1.000000,74.0,0.000000e+00,1.000000,74.0,0.000000e+00,...,0.0,0.0,1.0,74.0,0.0,74.0,0.0,0.0,0.0,0

In [5]:
# Seeing last 5 rows
traffic.tail()

,null,null.1,null.2,null.3,null.4,null.5,null.6,null.7,null.8,null.9,...,null.107,null.108,null.109,null.110,null.111,null.112,null.113,null.114,null.115,attack
764131,764132,18.897961,60.185845,3.594147,51.700968,60.182642,3.492246,257.391336,60.137137,2.455690,...,0.0,0.0,30682.136500,60.0,0.000004,60.000000,1.546141e-11,0.0,0.0,1
764132,764133,19.775173,60.176447,3.414055,52.499151,60.179163,3.426350,258.055986,60.136606,2.446246,...,0.0,0.0,30682.736491,60.0,0.000004,60.000000,1.500666e-11,0.0,0.0,1
764133,764134,20.692078,60.167920,3.250494,53.366680,60.175805,3.362736,258.838753,60.136078,2.436867,...,0.0,0.0,30683.478094,60.0,0.000004,60.000000,1.546141e-11,0.0,0.0,1
764134,764135,21.566383,60.160134,3.101020,54.171935,60.172560,3.301221,259.523519,60.135554,2.427549,...,0.0,0.0,30684.104181,60.0,0.000004,60.000000,1.591616e-11,0.0,0.0,1
764135,764136,1.089072,117.452795,49.127619,1.331557,114.114816,139.492735,2.837263,106.624655,938.448739,...,0.0,0.0,1.000000,119.0,0.000000,166.883193,0.000000e+00,0.0,0.0,1

In [6]:
# describe the data
traffic.describe()

,null,null.1,null.2,null.3,null.4,null.5,null.6,null.7,null.8,null.9,...,null.107,null.108,null.109,null.110,null.111,null.112,null.113,null.114,null.115,attack
count,764136.000000,764136.000000,764136.000000,764136.000000,764136.000000,764136.000000,764136.000000,764136.000000,764136.000000,764136.000000,...,764136.000000,764136.000000,764136.000000,764136.000000,764136.000000,764136.000000,7.641360e+05,764136.000000,764136.000000,764136.000000
mean,382068.500000,62.350762,66.255028,70.099174,89.739117,66.271720,94.559904,240.176000,66.290668,143.849892,...,-0.000486,-0.000098,20698.411614,66.377169,0.237334,68.730601,5.130033e+00,0.004659,0.000091,0.840840
std,220587.206986,44.615818,17.588593,1131.776556,59.838459,16.923905,1343.725625,141.576253,15.456532,1625.711793,...,0.649533,0.014717,13575.003636,19.792563,2.114585,23.244699,8.699055e+01,0.634564,0.009265,0.365826
min,1.000000,1.000000,42.000002,0.000000,1.000000,42.002371,0.000000,1.000000,44.291508,0.000000,...,-65.889400,-1.057362,1.000000,42.000000,0.000000,42.000000,0.000000e+00,-73.598530,-0.749841,0.000000
25%,191034.750000,7.951381,60.024847,0.236595,10.293426,60.051336,0.592575,22.328444,60.097114,1.363975,...,0.000000,0.000000,158.586108,60.000000,0.000002,60.000000,3.637979e-12,0.000000,0.000000,1.000000
50%,382068.500000,68.425090,60.078346,0.783348,100.562263,60.110449,1.338655,298.392953,60.135587,1.999527,...,0.000000,0.000000,30562.676349,60.000000,0.000004,60.000000,1.682565e-11,0.000000,0.000000,1.000000
75%,573102.250000,103.520470,60.745066,2.929853,142.195203,60.586357,3.576463,344.376752,61.130437,3.531308,...,0.000000,0.000000,30737.931083,60.000000,0.000007,72.000000,4.501999e-11,0.000000,0.000000,1.000000
max,764136.000000,144.071660,624.117403,442869.250128,195.788049,590.000000,400508.594984,425.179960,590.000000,265238.697696,...,92.778945,0.800243,30875.637639,1468.000000,130.141937,1468.000000,1.693692e+04,102.044062,0.875271,1.000000

In [7]:
# display all traffic
traffic

,null,null.1,null.2,null.3,null.4,null.5,null.6,null.7,null.8,null.9,...,null.107,null.108,null.109,null.110,null.111,null.112,null.113,null.114,null.115,attack
0,1,1.999983,60.000000,0.000000e+00,1.999990,60.000000,9.094947e-13,1.999997,60.000000,4.547474e-13,...,0.0,0.0,1.000000,60.0,0.000000,60.000000,0.000000e+00,0.0,0.0,0
1,2,1.000000,86.000000,0.000000e+00,1.000000,86.000000,0.000000e+00,1.000000,86.000000,0.000000e+00,...,0.0,0.0,1.000000,86.0,0.000000,86.000000,0.000000e+00,0.0,0.0,0
2,3,1.999272,86.000000,9.094947e-13,1.999563,86.000000,0.000000e+00,1.999854,86.000000,9.094947e-13,...,0.0,0.0,1.000000,86.0,0.000000,86.000000,0.000000e+00,0.0,0.0,0
3,4,1.000000,60.000000,0.000000e+00,1.000000,60.000000,0.000000e+00,1.000000,60.000000,0.000000e+00,...,0.0,0.0,1.000000,60.0,0.000000,60.000000,0.000000e+00,0.0,0.0,0
4,5,1.000000,74.000000,0.000000e+00,1.000000,74.000000,0.000000e+00,1.000000,74.000000,0.000000e+00,...,0.0,0.0,1.000000,74.0,0.000000,74.000000,0.000000e+00,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
764131,764132,18.897961,60.185845,3.594147e+00,51.700968,60.182642,3.492246e+00,257.391336,60.137137,2.455690e+00,...,0.0,0.0,30682.136500,60.0,0.000004,60.000000,1.546141e-11,0.0,0.0,1
764132,764133,19.775173,60.176447,3.414055e+00,52.499151,60.179163,3.426350e+00,258.055986,60.136606,2.446246e+00,...,0.0,0.0,30682.736491,60.0,0.000004,60.000000,1.500666e-11,0.0,0.0,1
764133,764134,20.692078,60.167920,3.250494e+00,53.366680,60.175805,3.362736e+00,258.838753,60.136078,2.436867e+00,...,0.0,0.0,30683.478094,60.0,0.000004,60.000000,1.546141e-11,0.0,0.0,1
764134,764135,21.566383,60.160134,3.101020e+00,54.171935,60.172560,3.301221e+00,259.523519,60.135554,2.427549e+00,...,0.0,0.0,30684.104181,60.0,0.000004,60.000000,1.591616e-11,0.0,0.0,1
764135,764136,1.089072,117.452795,4.912762e+01,1.331557,114.114816,1.394927e+02,2.837263,106.624655,9.384487e+02,...,0.0,0.0,1.000000,119.0,0.000000,166.883193,0.000000e+00,0.0,0.0,1

In [8]:
# Drop out all data except output set
X = traffic.drop(columns=["attack"])
# data without the Attack type
X

,null,null.1,null.2,null.3,null.4,null.5,null.6,null.7,null.8,null.9,...,null.106,null.107,null.108,null.109,null.110,null.111,null.112,null.113,null.114,null.115
0,1,1.999983,60.000000,0.000000e+00,1.999990,60.000000,9.094947e-13,1.999997,60.000000,4.547474e-13,...,0.000000e+00,0.0,0.0,1.000000,60.0,0.000000,60.000000,0.000000e+00,0.0,0.0
1,2,1.000000,86.000000,0.000000e+00,1.000000,86.000000,0.000000e+00,1.000000,86.000000,0.000000e+00,...,0.000000e+00,0.0,0.0,1.000000,86.0,0.000000,86.000000,0.000000e+00,0.0,0.0
2,3,1.999272,86.000000,9.094947e-13,1.999563,86.000000,0.000000e+00,1.999854,86.000000,9.094947e-13,...,0.000000e+00,0.0,0.0,1.000000,86.0,0.000000,86.000000,0.000000e+00,0.0,0.0
3,4,1.000000,60.000000,0.000000e+00,1.000000,60.000000,0.000000e+00,1.000000,60.000000,0.000000e+00,...,0.000000e+00,0.0,0.0,1.000000,60.0,0.000000,60.000000,0.000000e+00,0.0,0.0
4,5,1.000000,74.000000,0.000000e+00,1.000000,74.000000,0.000000e+00,1.000000,74.000000,0.000000e+00,...,0.000000e+00,0.0,0.0,1.000000,74.0,0.000000,74.000000,0.000000e+00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
764131,764132,18.897961,60.185845,3.594147e+00,51.700968,60.182642,3.492246e+00,257.391336,60.137137,2.455690e+00,...,5.456968e-12,0.0,0.0,30682.136500,60.0,0.000004,60.000000,1.546141e-11,0.0,0.0
764132,764133,19.775173,60.176447,3.414055e+00,52.499151,60.179163,3.426350e+00,258.055986,60.136606,2.446246e+00,...,4.547474e-12,0.0,0.0,30682.736491,60.0,0.000004,60.000000,1.500666e-11,0.0,0.0
764133,764134,20.692078,60.167920,3.250494e+00,53.366680,60.175805,3.362736e+00,258.838753,60.136078,2.436867e+00,...,5.002221e-12,0.0,0.0,30683.478094,60.0,0.000004,60.000000,1.546141e-11,0.0,0.0
764134,764135,21.566383,60.160134,3.101020e+00,54.171935,60.172560,3.301221e+00,259.523519,60.135554,2.427549e+00,...,5.002221e-12,0.0,0.0,30684.104181,60.0,0.000004,60.000000,1.591616e-11,0.0,0.0
764135,764136,1.089072,117.452795,4.912762e+01,1.331557,114.114816,1.394927e+02,2.837263,106.624655,9.384487e+02,...,0.000000e+00,0.0,0.0,1.000000,119.0,0.000000,166.883193,0.000000e+00,0.0,0.0

In [9]:
# set y to only be the attack
y = traffic['attack']
y

0         0
1         0
2         0
3         0
4         0
         ..
764131    1
764132    1
764133    1
764134    1
764135    1
Name: attack, Length: 764136, dtype: int64

In [10]:
# Split the data out into training and testing sets
#  everytime this is ran, we get a different training set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# setting the model to tbe a Decision tree
model = DecisionTreeClassifier()

# test the model with the input and output data
model.fit(X_train, y_train)
predictions = model.predict(X_test)

# test the accuracy of the data
score = accuracy_score(y_test, predictions)
# print Score value
print(f"The accuracy score is: {score}")

The accuracy score is: 1.0

In [11]:
# Seeing the f1_measure
f_measure = f1_score(y_test, predictions, average='weighted')
print(f"The f-measure is: {f_measure}")

The f-measure is: 1.0

In [12]:
# using joblib to store the model
joblib.dump(model, "mirai_attack_DT_classifier.joblib")

['mirai_attack_DT_classifier.joblib']

In [13]:
# picking out row to use for testing
row1 = X.iloc[764132]

row1

null        7.641330e+05
null.1      1.977517e+01
null.2      6.017645e+01
null.3      3.414055e+00
null.4      5.249915e+01
                ...
null.111    3.873843e-06
null.112    6.000000e+01
null.113    1.500666e-11
null.114    0.000000e+00
null.115    0.000000e+00
Name: 764132, Length: 116, dtype: float64

In [14]:
model.fit(X, y)
single_pred = model.predict([row1])
if single_pred[0] == 0:
    print("Normal Traffic")
elif single_pred[0] == 1:
    print("This is a Mirai attack")

This is a Mirai attack

In [16]:
# using the joblib file to recall model
dt_model = joblib.load("mirai_attack_DT_classifier.joblib")
predictions = dt_model.predict(X_test)
score = accuracy_score(y_test, predictions)
score

1.0